<!DOCTYPE HTML>
<html>

<head>
    <title>Privacy Notice | Dreams Wedding</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="main.css" />
    <link rel="shortcut icon" type="image/svg+xml" href="../assets/img/logos/LOGOTIPOS_B.svg">
</head>

<body class="is-preload">
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header">
            <a href="../"><img src="../assets/img/logos/dreams-wedding.png" alt=""></a>
            <nav id="nav">
                <ul>
                    <li><a href="../">Inicio</a></li>
                </ul>
            </nav>
        </header>

        <!-- Main -->
        <section id="main" class="container large">
            <header>
                <h2>Privacy Notice</h2>
                <p>Dreams Wedding</p>
            </header>
            <div class="box">
            <p>Club Vacacional Bac, S.A. de C.V. (hereinafter the “Responsible Party”), a company established under Mexican laws, with an address at Juan Ruiz de Alarcón number 2, Colonia Arcos Vallarta, Postal Code 44130, in Guadalajara, Jalisco, with a website dreams-wedding.com.mx, is responsible for the use and protection of personal data and, if applicable, sensitive data provided by individuals interested in acquiring a hotel product or service from the Responsible Party, hereinafter referred to as the “Holder”, in accordance with the provisions of the Federal Law on the Protection of Personal Data Held by Private Parties (the "Law"), and in this regard we inform you of the following:</p> <p><b>Purpose</b></p> <p>This Privacy Notice aims to regulate the use and protection of the Holder's personal data in possession of the Responsible Party in accordance with the Law.</p> <p><b>Purposes for which we will use your data</b></p> <p>The Holder's personal information will serve the Responsible Party to carry out its main activity and provide the hotel products or services that the Holder requests, requires, and/or may require. Likewise, this information will aim to identify the Holder for advice, attention, and follow-up; and may be disclosed exclusively to individuals deemed essential to carry out the activities or instruments necessary to fulfill the obligations derived from the Responsible Party's main activity. The disclosure of the provided data will be carried out according to the principles of consent, information, quality, purpose, loyalty, and proportionality. Additionally, it will serve as contact information, document preparation, strategy design, and, if applicable, collection.</p> <p>The personal data will be used appropriately for which they were obtained and may be integrated into a database, which will be created by the Responsible Party or a third party commissioned by them. This database will not be public and may contain additional data generated by proprietary means.</p> <p>Additionally, we will use your personal information for the following secondary purposes that are not necessary for the Responsible Party to provide the requested product or service but allow us to provide better attention:</p> <ul> <li>To inform or offer the Holder commercial and tourism promotions in general, as well as any other related products or services, including but not limited to, delivery of promotions, special services, informational brochures, surveys, and other products and services from the Responsible Party, its affiliated companies, and related projects.</li> <li>To record visitor activity on the aforementioned website.</li> <li>All those similar or analogous to the above.</li> </ul> <p>If you wish for your personal data not to be processed for these secondary purposes, you may inform us of this by sending an email to the address: gerencia@dreams-wedding.com.mx, mentioning the subject of this Privacy Notice in the email subject line.</p> <p>Your refusal to use your personal data for these secondary purposes will not be a reason for us to deny you the services and products you request or contract with the Responsible Party.</p> <p><b>What data we collect and where it is obtained from</b></p> <p>The personal data collected regarding the Holder are as follows: (i) name, (ii) business name or trade name, (iii) address(es), (iv) phone number(s), (v) email(s), (vi) Unique Population Registry Certificate, (vii) Federal Taxpayer Registry, and (viii) others permitted by the Law, for the purposes stated in this Privacy Notice. We may collect the Holder’s personal data in various ways: when you provide it directly to us; when you visit our address, website, or use our online services, and when we obtain information through other sources permitted by the Law.</p> <p><b>Data transfer</b></p> <p>All data transfers to our collaborators are carried out on the understanding that they assume the same obligations as the Responsible Party, in accordance with this Privacy Notice and the Law.</p> <p>The transfer of the Holder's personal information to third parties (other than our collaborators) will be done exclusively if you give your consent to provide it, except for information to financial institutions or authorities.</p> <p>Similarly, the Responsible Party may transfer data and personal information of the Holder to third parties with a direct or indirect relationship with the Responsible Party if necessary to carry out its activities.</p> <p>Additionally, the Responsible Party may transfer data and personal information of the Holder to its subsidiaries and affiliates, as well as to other companies related to the Responsible Party. This is to provide information and notices regarding their activities.</p> <p>The Holder will be considered to have given their consent, without any defect, for the transfer of personal data if they do not express their opposition, in accordance with the provisions of the third paragraph of Article 8 of the Law.</p> <p><b>Sensitive personal data</b></p> <p>We inform you that if sensitive personal data of the Holder is required, in accordance with the Law, the Responsible Party commits to treating such data under security measures, always guaranteeing its confidentiality and consent for the processing of your data. By using the aforementioned website, you consent and authorize that your sensitive personal data be processed according to the provisions of this Privacy Notice and as established by the Law.</p> <p><b>ARCO Rights</b></p> <p>You have the right to (i) know what personal data we have about you, how we use it, and the conditions of use (Access); (ii) request the correction of your personal information if it is outdated, inaccurate, or incomplete (Rectification); (iii) have it deleted from our records or databases when you believe it is not being used properly (Cancellation); (iv) and oppose the use of your personal data for specific purposes (Opposition). These rights are known as ARCO rights.</p> <p>For the Holder to exercise their ARCO rights over their personal data in possession of the Responsible Party, they must send an email to the following address: gerencia@dreams-wedding.com.mx, stating the reason and justification to access, rectify, cancel, and/or oppose the personal information.</p> <p>The Holder may revoke the consent they have given us for the processing of their personal data. However, it is important to note that in not all cases will we be able to attend to your request or immediately cease the use, as it is possible that, due to a legal obligation derived from the legal relationship with the Responsible Party, we may need to continue processing your personal data.</p> <p>To revoke your consent, as well as to know the procedure and requirements for such revocation, you must submit your request by sending a message to the email gerencia@dreams-wedding.com.mx.</p> <p>Similarly, in order for you to limit the use and disclosure of your personal information, you may send the request to the email gerencia@dreams-wedding.com.mx.</p> <p><b>Modifications to the Privacy Notice</b></p> <p>We reserve the right to make, at any time and without prior notice, modifications or updates to this Privacy Notice, to address legislative or jurisprudential developments, internal policies of the Responsible Party, new requirements for the provision or offering of our services or products, and market practices. These modifications may be communicated to the Holder through any of the following means: visible notices in our establishments or customer service centers, via email communication, or any other electronic means used to contact the Responsible Party, such as, but not limited to, the website dreams-wedding.com.mx, so it is recommended to periodically review our Privacy Notice.</p></div>
        </section>

        <!-- Footer -->
        <footer id="footer">
            <ul class="copyright">
                <li>Copyrights&copy; Dreams Wedding by Thy Collection 2020</li>
            </ul>
        </footer>

    </div>

    <!-- Scripts -->
    <script src="../assets/js/jquery.min.js"></script>
    <script src="../assets/js/browser.min.js"></script>
    <script src="../assets/js/breakpoints.min.js"></script>
    <script src="main.js"></script>

</body>

</html>